### ISSUE TITLE
jpg sent failed to become an embed

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#138]
Switched to a link.

https://makubot.s3.us-east-2/amazonaws.com/pictures/hatt/6ea27dc.jpg

**Comment by lupomikti** [comment]
This as well as issues [136](https://github.com/makusu2/makubot/issues/136) and [131](https://github.com/makusu2/makubot/issues/131) I believe are all related. I've discovered that new images/videos are not saving with the correct MIME-type; they get uploaded as `binary/...` instead of `image/...`. Because of this, the code run at [line 618 of picturecommands.py](https://github.com/makusu2/makubot/blob/8e0133fc2c908e9d53050b19efb3872f65a974e7/src/picturecommands.py#L618) always evaluates to true and causes the embed to be edited into a text message containing the url.

**Comment by makusu2** [comment]
Thanks @lupomikti !!!
This has been fixed for (almost) all existing images, and should be automatically fixed for all future images.
