### ISSUE TITLE
Fix howbig command

### ISSUE THREAD

**Issue by makusu2** [makusu2/makubot#141]
Apparently mb.mimi has had 55 commands for a while

**Comment by makusu2** [comment]
This might be a much bigger issue... It looks like there's only 55 pictures in /pictures/mimi, which would indicate that new pictures somehow aren't getting added successfully.

**Comment by lupomikti** [comment]
What's also strange is that this is only an issue for `mb.mimi` as I just tried with `mb.lupo` yesterday by doing `mb.howbig lupo`, adding images to it, then doing the howbig command again once they were approved. The howbig command worked as expected. It also appears to be working correctly for others. I suspect this might be related to filenames because the user who adds images to `mb.mimi` often uses screen snips that get named the same or similar things each time.

**Comment by makusu2** [comment]
:cry: 
Announcement time

**Comment by makusu2** [comment]
Turned out to be a much bigger issue; images were getting overwritten. It's bad, but it's fixed now ;~;
